#!/bin/bash

set -e
set -o pipefail

DISTRO=${DISTRO:-minideb}
FLAVORS=${FLAVORS:-jessie}
GCLOUD_PROJECT=${GCLOUF_PROJECT:-stacksmith-images}
GCLOUD_SERVICE_KEY=${GCLOUD_SERVICE_KEY:-}

for flavor in $FLAVORS
do
  revision=$(cat $flavor/REVISION)

  if [[ $DEV_BUILD ]]; then
    revision=DEV
  fi

  # build flavor tag
  docker build --rm=false -t gcr.io/$GCLOUD_PROJECT/$DISTRO:$flavor-r$revision -f $flavor/Dockerfile .
  echo -e "FROM gcr.io/$GCLOUD_PROJECT/$DISTRO:$flavor-r$revision\n$(cat $flavor/buildpack/Dockerfile)" | docker build --rm=false -t gcr.io/$GCLOUD_PROJECT/$DISTRO-buildpack:$flavor-r$revision -

  # build rolling tag
  if [[ $revision != "DEV" ]]; then
    docker build --rm=false -t gcr.io/$GCLOUD_PROJECT/$DISTRO:$flavor -f $flavor/Dockerfile .
    echo -e "FROM gcr.io/$GCLOUD_PROJECT/$DISTRO:$flavor\n$(cat $flavor/buildpack/Dockerfile)" | docker build --rm=false -t gcr.io/$GCLOUD_PROJECT/$DISTRO-buildpack:$flavor -
  fi
done
