#!/bin/bash

BITNAMI_PREFIX=/opt/bitnami
UPDATE_SERVER="https://container.checkforupdates.com"
CURL_ARGS="-sLf --connect-timeout 1 --speed-time 1 --speed-limit 1024"

# Color Palette
RESET='\033[0m'

## Foreground
BLACK='\033[38;5;0m'
RED='\033[38;5;1m'
GREEN='\033[38;5;2m'
YELLOW='\033[38;5;3m'
BLUE='\033[38;5;4m'
MAGENTA='\033[38;5;5m'
CYAN='\033[38;5;6m'
WHITE='\033[38;5;7m'

## Background
ON_BLACK='\033[48;5;0m'
ON_RED='\033[48;5;1m'
ON_GREEN='\033[48;5;2m'
ON_YELLOW='\033[48;5;3m'
ON_BLUE='\033[48;5;4m'
ON_MAGENTA='\033[48;5;5m'
ON_CYAN='\033[48;5;6m'
ON_WHITE='\033[48;5;7m'

MODULE="$(basename $0)"

log() {
  echo -e "${DEBUG:+${CYAN}${MODULE} ${MAGENTA}$(date "+%H:%M:%S ")}${RESET}${@}" >&2
}

info() {
  log "${GREEN}INFO ${RESET} ==> ${@}"
}

warn() {
  log "${YELLOW}WARN ${RESET} ==> ${@}"
}

error() {
  log "${RED}ERROR${RESET} ==> ${@}"
}

print_welcome_page() {
  if [ -z "$DISABLE_WELCOME_MESSAGE" ]; then
    if [ -n "$BITNAMI_APP_NAME" ]; then
      print_image_welcome_page
    elif [ -n "$STACKSMITH_STACK_ID" ]; then
      print_stacksmith_welcome_page
    fi
  fi
}

check_for_updates() {
  if [ -z "$DISABLE_LAUNCH_TRACKING" ]; then
    if [ -n "$BITNAMI_APP_NAME" ]; then
      check_for_image_updates
    elif [ -n "$STACKSMITH_STACK_ID" ]; then
      check_for_stack_updates
    fi
  fi
}

# Prints the welcome page for this Bitnami Docker image
print_image_welcome_page() {
  GITHUB_PAGE=https://github.com/bitnami/bitnami-docker-${BITNAMI_APP_NAME}
cat >&2 << EndOfMessage

  *** Welcome to the ${BITNAMI_APP_NAME} image ***
  *** Brought to you by Bitnami ***
  *** More information: ${GITHUB_PAGE} ***
  *** Issues: ${GITHUB_PAGE}/issues ***

EndOfMessage
}

# Prints the welcome page for this Stacksmith stack
print_stacksmith_welcome_page() {
  STACKSMITH_URL="https://stacksmith.bitnami.com"
  STACKSMITH_STACK_URL="$STACKSMITH_URL/dashboard/stacks/$STACKSMITH_STACK_ID"

  if [ "$STACKSMITH_STACK_PRIVATE" ]; then
    MSG1="Go to $STACKSMITH_STACK_URL to manage your stack."
  else
    MSG1="This stack was created anonymously."
    MSG2="Sign up for a free account at $STACKSMITH_URL to manage and regenerate your stacks."
  fi

  cat >&2 << EndOfMessage

  *** Welcome to your $STACKSMITH_STACK_NAME container! ***
  *** Brought to you by Bitnami. ***
  *** $MSG1 ***
  *** $MSG2 ***

EndOfMessage
}

detect_cloud() {
  local CLOUD=unknown
  if curl $CURL_ARGS -o /dev/null http://instance-data/latest/meta-data/; then
    CLOUD=aws
  elif curl $CURL_ARGS -o /dev/null http://metadata.google.internal/0.1/meta-data/; then
    CLOUD=google
  elif curl $CURL_ARGS -o /dev/null http://169.254.169.254/metadata/v1/InstanceInfo; then
    CLOUD=azure
  elif curl $CURL_ARGS -o /dev/null http://169.254.169.254/metadata/v1/vendor-data; then
    CLOUD=do
  fi
  echo $CLOUD
}

detect_platform() {
  local PLATFORM=unknown
  if curl $CURL_ARGS -o /dev/null http://$(curl $CURL_ARGS http://instance-data/latest/meta-data/hostname):51678/v1/metadata; then
    PLATFORM=ecs
  elif [ -f /var/run/secrets/kubernetes.io/serviceaccount/namespace ]; then
    PLATFORM=kubernetes
  elif [ -n "$CHE_API" ]; then
    # CHE_API is set by Eclipse Che and Codenvy as of version 5.0.0-M8
    if [ "$CHE_API" == "https://codenvy.io/api" ]; then
      PLATFORM=codenvy
    else
      PLATFORM=che
    fi
  fi
  echo $PLATFORM
}

# Checks for any updates for this Stacksmith stack
check_for_stack_updates() {
  ORIGIN=${BITNAMI_CONTAINER_ORIGIN:-stacksmith}
  CLOUD=${BITNAMI_CONTAINER_CLOUD:-$(detect_cloud)}
  PLATFORM=${BITNAMI_CONTAINER_PLATFORM:-$(detect_platform)}

  RESPONSE=$(curl -s --connect-timeout 20 \
    --cacert /opt/bitnami/updates-ca-cert.pem \
    "$UPDATE_SERVER/api/v1?image=$STACKSMITH_STACK_ID&origin=$ORIGIN&cloud=$CLOUD&platform=$PLATFORM" \
    -w "|%{http_code}")

  if [ -z "$DISABLE_UPDATE_MESSAGE" ]; then
    STATUS=$(echo $RESPONSE | cut -d '|' -f 2)

    ACTION="go to https://stacksmith.bitnami.com/dashboard/stacks/"
    REGENERATE_ACTION="$ACTION$STACKSMITH_STACK_ID to regenerate"
    RECREATE_ACTION="${ACTION}new to create a new stack"

    if [ -z "$STACKSMITH_STACK_PRIVATE" ]; then
      # Can't regenerate if it's an anonymous stack
      REGENERATE_ACTION=$RECREATE_ACTION
    fi

    OUTDATED_MSG="Updates available"
    VULNERABLE_MSG="Your stack is vulnerable"

    case "$STATUS" in
      200 )
        FORMAT="${BLACK}${ON_GREEN}"
        MSG="Your stack is up to date!"
        ;;
      201 )
        FORMAT="${BLACK}${ON_YELLOW}"
        MSG="$OUTDATED_MSG: $REGENERATE_ACTION"
        ;;
      204 )
        FORMAT="${BLACK}${ON_YELLOW}"
        MSG="$OUTDATED_MSG: $RECREATE_ACTION"
        ;;
      426 )
        FORMAT="${WHITE}${ON_RED}"
        MSG="$VULNERABLE_MSG: $REGENERATE_ACTION"
        ;;
      423 )
        FORMAT="${WHITE}${ON_RED}"
        MSG="$VULNERABLE_MSG: $RECREATE_ACTION"
        ;;
    esac

    if [ "$MSG" ]; then
      log "\n${FORMAT}*** ${MSG} ***${RESET}\n"
    fi
  fi
}

# Checks for any updates for this Bitnami Docker image
check_for_image_updates() {
  ORIGIN=${BITNAMI_CONTAINER_ORIGIN:-DHR}
  CLOUD=${BITNAMI_CONTAINER_CLOUD:-$(detect_cloud)}
  PLATFORM=${BITNAMI_CONTAINER_PLATFORM:-$(detect_platform)}

  case "$PLATFORM" in
    che|codenvy ) DISABLE_UPDATE_MESSAGE=1 ;; # disable update message displayed when running on che
  esac

  RESPONSE=$(curl -s --connect-timeout 20 \
    --cacert $BITNAMI_PREFIX/updates-ca-cert.pem \
    "$UPDATE_SERVER/api/v1?image=$BITNAMI_APP_NAME&version=$BITNAMI_IMAGE_VERSION&origin=$ORIGIN&cloud=$CLOUD&platform=$PLATFORM" \
    -w "|%{http_code}")

  if [ -z "$DISABLE_UPDATE_MESSAGE" ]; then
    VERSION=$(echo $RESPONSE | cut -d '|' -f 1)
    if [[ ! $VERSION =~ [0-9.-] ]]; then
      return
    fi

    STATUS=$(echo $RESPONSE | cut -d '|' -f 2)

    case "$STATUS" in
      200 )
        FORMAT="${BLACK}${ON_GREEN}"
        MSG="Your container is up to date!"
        ;;
      201 )
        FORMAT="${BLACK}${ON_YELLOW}"
        MSG="New version available: run docker pull bitnami/$BITNAMI_APP_NAME:$VERSION to update."
        ;;
    esac

    if [ -n "$MSG" ]; then
      log "\n${FORMAT}*** ${MSG} ***${RESET}\n"
    fi
  fi
}
